import { ApiPodcast } from "@/infrastructure/types/ApiPodcast";

export const apiPodcastMock: ApiPodcast = {
  resultCount: 2,
  results: [
    {
      wrapperType: "track",
      kind: "podcast",
      collectionId: 1,
      trackId: 1,
      artistName: "Artist",
      collectionName: "Filete",
      trackName: "Filete",
      collectionViewUrl: "https://podcasts.apple.com/us/podcast/filete/id1",
      feedUrl: "https://feed.url",
      trackViewUrl: "https://podcasts.apple.com/us/podcast/filete/id1",
      artworkUrl30: "ImageUrl",
      artworkUrl60: "ImageUrl",
      artworkUrl100: "ImageUrl",
      releaseDate: "2024-01-01T00:00:00Z",
      collectionExplicitness: "notExplicit",
      trackExplicitness: "notExplicit",
      trackCount: 1,
      country: "USA",
      primaryGenreName: "Podcast",
      contentAdvisoryRating: "Clean",
      artworkUrl600: "ImageUrl",
      collectionCensoredName: "",
      trackCensoredName: "",
      artworkUrl160: "",
      genreIds: [],
      genres: [],
      episodeUrl: "",
      description: "",
      shortDescription: "",
      artistIds: [],
      episodeGuid: "",
      episodeFileExtension: "",
      episodeContentType: "",
      trackTimeMillis: 0,
      closedCaptioning: "",
      previewUrl: ""
    },
    {
      wrapperType: "podcastEpisode",
      kind: "podcast-episode",
      collectionId: 1,
      trackId: 1,
      artistName: "Artist",
      collectionName: "Filete",
      trackName: "Title",
      description: "Description",
      releaseDate: "2024-01-01T00:00:00Z",
      trackTimeMillis: 100000,
      episodeUrl: "AudioUrl",
      artworkUrl600: "ImageUrl",
      previewUrl: "AudioUrl",
      collectionViewUrl: "https://podcasts.apple.com/us/podcast/filete/id1",
      trackViewUrl: "https://podcasts.apple.com/us/podcast/filete/id1?i=1",
      feedUrl: "https://feed.url",
      collectionCensoredName: "",
      trackCensoredName: "",
      artworkUrl30: "",
      artworkUrl60: "",
      artworkUrl100: "",
      collectionExplicitness: "",
      trackExplicitness: "",
      trackCount: 0,
      country: "",
      primaryGenreName: "",
      contentAdvisoryRating: "",
      artworkUrl160: "",
      genreIds: [],
      genres: [],
      shortDescription: "",
      artistIds: [],
      episodeGuid: "",
      episodeFileExtension: "",
      episodeContentType: "",
      closedCaptioning: ""
    }
  ],
};
